name: Submit a checkbox job to Testflinger
on:
    push:
        branches: [test-action-fling-test]
    workflow_dispatch:

jobs:
  checkbox-canary-test:
    runs-on: [self-hosted, testflinger]
    strategy:
      fail-fast: false
      matrix:
        include:
          - checkbox_runtime: checkbox16
            data_source: "distro: xenial"
            checkbox_track: uc16
            arch: amd64
            queue: hp-elitebook-850-g7-notebook-pc

    steps:
    - name: Checkout checkbox monorepo
      uses: actions/checkout@v4

    - name: Create job
      id: create-job
      uses: ./.github/actions/create-checkbox-canary-test-job
      with:
        queue: ${{ matrix.queue }}
        data_source: ${{ matrix.data_source }}
        checkbox_runtime: ${{ matrix.checkbox_runtime }}
        checkbox_track: ${{ matrix.checkbox_track }}
    
    - name: Verify job
      shell: bash
      run:
        cat ${{ steps.create-job.outputs.job }}

    - name: Submit job
      uses: canonical/testflinger/.github/actions/submit@CERTTF-327-github-action-submit
      with:
        dry-run: true
        poll: false
        job-path: ${{ steps.create-job.outputs.job }}
