name: Submit a checkbox job to Testflinger (job provided inline)
on:
    push:
        branches: [machine-pool-poc]
    workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: [self-hosted]
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Create matrix
        id: create-matrix
        run: |
          echo '[
            {
              "queue": "hp-elitebook-850-g7-notebook-pc",
              "data_source": "distro: jammy",
              "checkbox_runtime": "checkbox22",
              "checkbox_track": "uc22"
            },
            {
              "queue": "hp-elitebook-850-g7-notebook-pc",
              "data_source": "distro: jammy"
            }
          ]' > matrix.json
      - name: Set matrix output
        id: set-matrix
        run: |
          echo "matrix=$(jq -cn --argjson matrix "$(cat matrix.json)" '{include: $matrix}' | jq -R)" >> $GITHUB_OUTPUT
          echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
  checkbox-promotion-beta-to-candidate-test:
    needs: generate-matrix
    runs-on: [self-hosted, testflinger]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: diagnostics
        run: |
          echo "Matrix - Project ${{ matrix.project }}, Config ${{ matrix.config }}"
          #echo ${{ matrix.queue }}
          #echo ${{ matrix.data_source }}
          #echo ${{ matrix.checkbox_runtime }}
          #echo ${{ matrix.checkbox_track }} 
