name: Promote Checkbox beta to candidate
on:
    workflow_dispatch:

jobs:
  checkbox-promotion-beta-to-candidate-test:
    runs-on: [self-hosted, testflinger]
    strategy:
      fail-fast: false
      matrix:
        include:
          #- queue: 201712-26047
          #  provision_data: "distro: xenial"
          #  checkbox_runtime: checkbox16
          #  checkbox_track: uc16

          #- queue: 201712-26047
          #  provision_data: "distro: focal"
          #  checkbox_runtime: checkbox20
          #  checkbox_track: uc20

          #- queue: 201712-26047
          #  provision_data: "distro: bionic"

          - queue: 202203-30061
            provision_data: "distro: jammy"
            checkbox_runtime: checkbox22
            checkbox_track: uc22

            #- queue: 202203-30061
          #  provision_data: "distro: jammy"

          #- queue: 202012-28526
          #  provision_data: "distro: noble"
          #  checkbox_runtime: checkbox24
          #  checkbox_track: uc24

          #- queue: 202012-28526
          #  provision_data: "distro: noble"

          #- queue: 202201-29865
          #  provision_data: "distro: bionic"
          #  checkbox_runtime: checkbox18
          #  checkbox_track: uc18

          #- queue: 202201-29865
          #  provision_data: "distro: focal"

          # - queue: rpi4b
          #   provision_data: "url: http://cdimage.ubuntu.com/ubuntu-core/22/dangerous-stable/current/ubuntu-core-22-arm64+raspi.img.xz"
          #   checkbox_runtime: checkbox22
          #   checkbox_track: uc22

          # - queue: rpi4b
          #     provision_data: "url: http://cdimage.ubuntu.com/ubuntu-core/22/dangerous-stable/current/ubuntu-core-22-armhf+raspi.img.xz"
          #     checkbox_runtime: checkbox22
          #     checkbox_track: uc22
    steps:
    - name: Checkout checkbox monorepo
      uses: actions/checkout@v4

    - name: Run the spec
      uses: canonical/checkbox/.github/actions/checkbox_source_deb@main
      with:
        provision_data: ${{ matrix.spec.provision_data }}
        queue: ${{ matrix.spec.queue }}
        test_plan: ${{ matrix.spec.test_plan }}
        match: ${{ matrix.spec.match }}
        zapper_channel: ${{ matrix.spec.zapper_channel }}
        launcher_override: |
          [environment]
          WPA_BG_PSK = ${{ secrets.INPUT_PASSWORD_SECRET }}
          WPA_N_PSK = ${{ secrets.INPUT_PASSWORD_SECRET }}
          WPA_AC_PSK = ${{ secrets.INPUT_PASSWORD_SECRET }}
          WPA_AX_PSK = ${{ secrets.INPUT_PASSWORD_SECRET }}
          WPA3_AX_PSK = ${{ secrets.INPUT_PASSWORD_SECRET }}
        checkbox_revision: ${{ steps.get_sha.outputs.sha }}
